// Generates generated/routes.js — the route allowlist the Worker uses to tell a
// real page from a 404. Derived from src/seo-build.js so it cannot drift.
import { writeFileSync, mkdirSync } from 'node:fs'
import { ALL_ROUTES } from '../src/seo-build.js'

mkdirSync(new URL('../generated', import.meta.url), { recursive: true })
const out = new URL('../generated/routes.js', import.meta.url)

writeFileSync(out, `// GENERATED by scripts/gen-routes.mjs — do not edit by hand.
export const ROUTES = new Set(${JSON.stringify(ALL_ROUTES.sort(), null, 2)})
`)
console.log(`routes.js: ${ALL_ROUTES.length} routes`)
